name: drinkapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  http: ^1.1.0
  carousel_slider: ^4.2.1
  curved_navigation_bar: ^1.0.3
  draggable_home: ^1.0.2
  pinput: ^3.0.0
  draggable_bottom_sheet: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/plash_image/
    - assets/images/begin_image/
    - assets/images/signin-signup_image/
    - assets/images/home_image/

  fonts:
    - family: Caprasimo
      fonts:
        - asset: assets/fonts/Caprasimo-Regular.ttf
          style: italic
